spring:
  jpa:
    database: mysql
    defer-datasource-initialization: false
    generate-ddl: true
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyComponentPathImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        default_schema: dbo
        format_sql: true
        show_sql: true

  datasource:
    url: jdbc:mariadb://localhost:3306/testdb
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: perlhash


logging:
  level:
    org.springframework.security: TRACE
