spring:
  jpa:
    database: mysql
    defer-datasource-initialization: false
    generate-ddl: true
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyComponentPathImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        default_schema: dbo

  datasource:
    embedded-database-connection: none
#    url : jdbc:mariadb://localhost:3306/testdb
#    driver-class-name: org.mariadb.jdbc.Driver
#    username: root
#    password: perlhash
    url: jdbc:h2:mem:test;INIT=CREATE SCHEMA IF NOT EXISTS DBO;
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  h2:
    console:
      enabled: true
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration